markdown: kramdown
highlighter: pygments

exclude: [Vagrantfile, vendor]

paginate: 5

title: HauteLook Technology
url: http://hautelook.github.io/
baseurl: /
blog: "<a href='/'>blog</a>"
feed: "<a href='/atom.xml'>atom feed</a>"
