markdown: kramdown

kramdown:
  input: GFM

exclude: [Vagrantfile, vendor]

title: HauteLook Technology
url: http://hautelook.github.io/
baseurl: /
blog: "<a href='/'>blog</a>"
feed: "<a href='/atom.xml'>atom feed</a>"
